add_newline = false

[aws]
symbol = "AWS "

[dotnet]
symbol = ".NET "

[git_status]
# disabled for extra large repositories (over 10,000 commits)
disabled = true

[golang]
symbol = "Go "

[line_break]
disabled = true

[nodejs]
symbol = "NodeJS "

[package]
symbol = ""

[ruby]
symbol = "Ruby "

[rust]
symbol = "Rust "
